<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

1. Python Lists

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

2. Numpy Arrays

In [8]:
import numpy as np

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

3. Dictionary

In [3]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
} # string before the colon is the key, string after is the value

- Dictionaries use a key and an associated value separated by a :
- The dictionary holds the real and superhero names in one structure while we need two lists (or arrays) for the same data.
- For lists and arrays, the order matters. I.e. ‘Iron Man’ must be in the same position as ‘Tony Stark’ for things to work.

## 1.2 Accessing data from a list (or array)

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [14]:
py_real_names[1]

'Tony Stark'

In [15]:
py_super_names[1]

'Iron Man'

In [17]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [18]:
py_super_names[-2]   # Reverse indexing

'Iron Man'

## 1.3 Accessing data from a dictionary

In [19]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [20]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [24]:
superhero_info.keys() # access all the keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [23]:
superhero_info.values() # access all the values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [25]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [27]:
py_superhero_info[0][1]

'Black Widow'

# 2 Lists vs. Arrays

## 2.1 Size

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

**Lists**

In [11]:
len(py_list_2d) # length of list

10

**Arrays**

In [12]:
len(np_array_2d) # length of array

10

In [42]:
np_array_2d.shape

(10, 2)

- Shape is not a function, it is a property or attribute of the NumPy array.

## 2.2 Arrays are fussy about type

- One difference between lists and arrays is that arrays insist on having only a single data type, lists are more accommodating.

In [15]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

**Lists**

In [37]:
py_list

[1, 1.5, 'A']

**Arrays**

In [16]:
np_array # array converts all elements to one type

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

**Lists**

In [19]:
py_list + 10        # Won't work! We cannot add an integer to a python list as compared to a numpy array

TypeError: can only concatenate list (not "int") to list

**Arrays**

In [20]:
np_array + 10 # Adding an integer to numpy array will add the integer to every element in the array

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

**Lists**

In [23]:
py_list_1 + py_list_2 # Adding two python lists will concatenate the two lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [24]:
np_array_1 + np_array_2 # Adding two numpy array will add the elements with matching indices 

array([11, 22, 33, 44, 55])

- Adding lists causes them to grow while adding arrays is an element-wise operation.

## 2.5 Multiplying by a Number

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [25]:
py_list*2 # Mupltiplying a python list by a constant n will concatenate n copies of the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays**

In [27]:
np_array*2 # multiplying a numpy array by constant n will multiply the elements in the array by n

array([ 2,  4,  6,  8, 10])

- Multiplying by a number makes a list grow, whereas an array multiplies its elements by the number!

## 2.6 Squaring

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

**Lists**

In [55]:
py_list**2                      # Won't work!

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Arrays**

In [28]:
np_array**2 # Squaring a numpy array will square the elements in the array

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [57]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [58]:
py_list == 3     # Works, but what IS the question?

False

In [64]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

**Arrays**

In [61]:
np_array == 3

array([False, False,  True, False, False])

In [63]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [65]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [67]:
sum(py_list)     # sum() is a base Python function

15

In [68]:
max(py_list)     # max() is a base Python function

5

In [69]:
min(py_list)     # min() is a base Python function

1

In [75]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

**Arrays**

In [70]:
np_array.sum()

15

In [71]:
np_array.max()

5

In [72]:
np_array.min()

1

In [73]:
np_array.mean()

3.0

In [74]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes