<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- Subsetting means to ‘select’.
- Indexing refers to selecting one element.
- Slicing refers to selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

| Syntax    | Result                          |                                 | Note                                     |
|-----------|---------------------------------|---------------------------------|------------------------------------------|
| x[0]      | First element                   | 'a1'                            |                                          |
| x[-1]     | Last element                    | 'j10'                           |                                          |
| x[0:3]    | Index 0 to 2                    | ['a1','b2','c3']                | Gives  3 − 0 = 3 elements                |
| x[1:6]    | Index 1 to 5                    | ['b2','c3','d4','e5','f6']      | Gives  6 − 1 = 5 elements                |
| x[1:6:2]  | Index 1 to 5 in steps of 2      | ['b2','d4','f6']                | Gives every other of  6 − 1 = 5 elements |
| x[5:]     | Index 5 to the end              | ['f6','g7','h8','i9','j10']     | Gives len(x) − 5 = 5 elements            |
| x[:5]     | Index 0 to 5                    | ['a1','b2','c3','d4','e5']      | Gives  5 − 0 = 5 elements                |
| x[5:2:-1] | Index 5 to 3 (i.e., in reverse) | ['f6','e5','d4']                | Gives  5 − 2 = 3 elements                |
| x[::-1]   | Reverses the list               | ['j10','i9','h8',...,'b2','a1'] |                                          |

## 1.2 Arrays only | Subsetting by masking

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3 # Creates a mask with indices where the element is >3 is True otherwise False
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [4]:
np_array[my_mask] # Applies mask on np_array

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [8]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [9]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [6]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

**Example 1**

In [7]:
py_list_2d[3] # 4th element 

[4, 'D']

In [15]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

**Example 2**

In [16]:
py_list_2d[3][0]

4

In [17]:
np_array_2d[3, 0]

'4'

- Notice how the syntax for arrays uses just a single pair of square brackets ([ ]).

**Example 3**

In [19]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [20]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

**Example 4**

In [8]:
py_list_2d[:3][0] # [:3] slices a list from index 0 to 2, then [0] extracts the first element of the new list

[1, 'A']

In [22]:
np_array_2d[:3, 0] # extracts elements with index [0] inside each list elements up to the list with index =2

array(['1', '2', '3'], dtype='<U11')

**Example 5**

In [9]:
py_list_2d[3:6][0] # [3:6] slices a list from index 3 to 5, then [0] extracts the first element of the new list

[4, 'D']

In [25]:
np_array_2d[3:6, 0] # extracts elements with index [0] inside each list elements up to the list with index from 3 to 5

array(['4', '5', '6'], dtype='<U11')

In [10]:
np_array_2d[:, 0] # extracts elements with index [0] inside each list elements

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [27]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [30]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [31]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [32]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

**The version with append() runs about 1.5 times faster than the rest!**

In [33]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [34]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [11]:
x=[1, 2, 3]
x.append([4, 5, 6]) # Appending list A to another list B will add list A as an element in list B
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

**Tuples are similar to lists, except they use ( ) and cannot be changed after creation (i.e., they are immutable).**

In [36]:
a=(1, 2, 3)     # Define tuple

In [37]:
print(a[0])    # Access data

1


In [39]:
# The following will NOT work
a[0]=-1

TypeError: 'tuple' object does not support item assignment

In [40]:
a[0]+= [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [46]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [47]:
x=[1, 2, 3]
y=x.copy()    # DO this!
z=x.copy()    # DO this!

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes